project:
  type: website

website:
  title: "alugue-ap.com"
  site-url: https://alugue-ap.com/
  favicon: "images/site.png"
  twitter-card: true
  open-graph: true

  page-footer:
    background: "#000000"
    #background: light
    left: |
      [Termos e Condições](/ts-and-cs.qmd)
    center: |
      Developed by [Nion M. Dransfeld](https://nionmaron.com)
    border: false
  navbar:
    background: "#2E8BC0"



format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

execute: 
  freeze: auto
  