project:
  type: website

website:
  title: "alugue-ap.com"
  back-to-top-navigation: false
  site-url: https://alugue-ap.com/
  favicon: "images/site.png"
  twitter-card: true
  open-graph: true
  google-analytics: "G-JMQK6TVF6H"

  page-footer:
    background: "#000000"
    #background: light
    left: |
      [Termos e Condições](/ts-and-cs.qmd)
    border: false

  navbar:
    search: false
    background: "#2E8BC0"
    right: 
       - text: "Acesso"
         file: login.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

execute: 
  freeze: auto
  
  

